services:
  worker:
    build: .
    command: go run main.go work
    depends_on:
      - redis
    environment:
      - REDIS_ADDRS=redis:6379
      - INVENTORY_ADDRESS=inventory:8080/streams.json
  enqueuer:
    build: .
    command: go run main.go enqueue
    depends_on:
      - redis
    environment:
      - REDIS_ADDRS=redis:6379
      - INVENTORY_ADDRESS=http://inventory:8080/streams.json
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  video-api:
    image: python:3.9-alpine
    command: python3 -m http.server -d /testvideo 8080
    volumes:
      - ./testvideo:/testvideo
    ports:
      - "8080:8080"
