services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./:/app
    entrypoint: ["video_samples", "generate", "--streamsFile", "/app/streams.json"]
    depends_on:
      - store
    env_file:
      - .env

  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8181:8181"
    command: ["go", "run", "main.go", "server"]
    depends_on:
      - store
    env_file:
      - .env

  store:
    image: redis
    ports:
      - "6379:6379"

  video:
    build:
      context: ./video
    entrypoint: ''
    volumes:
      - "./video/OpenSans-Bold.ttf:/video/OpenSans-Bold.ttf"
    ports:
      - "8080:8080"
