services:
  samples_generator:
    build: .
    volumes:
      - ./:/app
    command: ["go", "run", "main.go", "generate"]
    depends_on:
      - store
      - video
    env_file:
      - .env

  samples_server:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8181:8181"
    command: ["go", "run", "main.go", "server"]
    depends_on:
      - store
      - video
    env_file:
      - .env

  store:
    image: redis
    ports:
      - "6379:6379"

  video:
    build:
      context: ./video
    volumes:
      - "./video/OpenSans-Bold.ttf:/video/OpenSans-Bold.ttf"
    ports:
      - "8080:8080"
